### ISSUE TITLE
TestFlight release

### ISSUE THREAD

**Issue by luke2m** [atomheartother/jellyfin-audio#1]
Hello! I'm looking for a Jellyfin music client for iOS. What is the status of this project? Would you consider publishing it to testflight if you are able to? I would be up to testing, but don't have access to a Mac.

**Comment by atomheartother** [comment]
Hey, this is a small side-project of mine I started a while ago, and never got around to actually developing properly, so the status is about "On indefinite hold", at least until jellyfin releases proper documentation so I don't have to reverse-engineer their API myself, because the effort is definitely not worth it with all the other clients currently out there.
